name: Corono Runner Animation

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  update-animation:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Update README with animation
        run: |
          echo "## Corono Runner" >> README.md
          echo "![Corono Runner Animation](https://example.com/animation.gif)" >> README.md
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add README.md
          git commit -m "Update README with Corono Runner animation"
          git push
