name: Generate Snake

on:
  schedule:
    - cron: "0 */6 * * *" # Her 6 saatte bir çalışır
  workflow_dispatch: # Manuel tetikleme için

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: Platane/snk@v3
      id: snake-gif
      with:
        github_user_name: SERAP-KEREM
        gif_out_path: dist/github-contribution-grid-snake.gif
        svg_out_path: dist/github-contribution-grid-snake.svg

    - name: Push changes
      uses: ad-m/github-push-action@v0.6.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: output
        force: true

    - uses: crazy-max/ghaction-github-pages@v2.1.3
      with:
        target_branch: output
        build_dir: dist
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
