name: GitHub-Profile-3D-Contrib

on:
  schedule:  # 03:00 JST 18:00 UTC
    - cron: "0 18 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      - uses: actions/checkout@v3

      - uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ github.repository_owner }}  # Bu satırı düzelttim

      - name: Commit & Push
        run: |
          git config user.name "github-actions"  # Yazım hatasını düzelttim
          git config user.email "github-actions@github.com"
          git add -A  # Aradaki boşluğu kaldırdım
          git commit -m "generated"  # Doğru commit mesajı
          git push
